### ISSUE TITLE
TranslateError: No translation get, you may retry

### ISSUE THREAD

**Issue by ChillarAnand** [littlecodersh/translation#4]
The default example fails with 

```py
In [6]: print(baidu('hello world!', dst = 'ru'))
---------------------------------------------------------------------------
TranslateError                            Traceback (most recent call last)
<ipython-input-6-62aeea8f76b9> in <module>()
----> 1 print(baidu('hello world!', dst = 'ru'))

/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/translation/__init__.py in baidu(text, src, dst, proxies)
     26 def baidu(text, src = None, dst = None, proxies = None):
     27     return t.get(text, default = 'baidu', src = src,
---> 28         dst = dst, proxies = proxies)
     29 def bing(text, src = None, dst = None, proxies = None):
     30     return t.get(text, default = 'bing', src = src,

/home/chillaranand/.virtualenvs/py35/lib/python3.5/site-packages/translation/main.py in get(self, text, default, src, dst, proxies)
     31         test_proxies(proxies, default)
     32         r =  TRANSLATION_DICT[default](text, src, dst, proxies)
---> 33         if r == '': raise TranslateError('No translation get, you may retry')
     34         return r
     35     def get_all(self, text, default = None, src = None,

TranslateError: No translation get, you may retry
```

**Comment by nikitha-r** [comment]
Very basic is not working. Please help me with this. 

![translate_error](https://user-images.githubusercontent.com/13657210/27624143-7153c376-5bad-11e7-870c-2717b984df3a.png)

**Comment by hugovk** [comment]
Same here, but at least `bing` is working:

```python
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from translation import baidu, google, youdao, iciba, bing

>>> print(baidu('hello world!', dst = 'ru'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/translation/__init__.py", line 28, in baidu
    dst = dst, proxies = proxies)
  File "/usr/local/lib/python2.7/site-packages/translation/main.py", line 33, in get
    if r == '': raise TranslateError('No translation get, you may retry')
translation.exception.TranslateError: No translation get, you may retry

>>> print(bing('hello world!', dst = 'ru'))
Всем привет!
>>>
```

**Comment by Paethon** [comment]
I get exactly the same error for most translation engines. Others are failing with connection errors. Unfortunately, for me none of the engines work ... :(

**Comment by dadadidodi** [comment]
yep. none of those engines works

**Comment by 1uciuszzz** [comment]
none of the engines work

**Comment by yingjinghuang** [comment]
none of the engines work
